### PR TITLE
fix(email): add a script to send a string update message to the l10n list

### LINKED ISSUE #56: Automatically draft new-strings announcement emails for dev-l10n
As noted in https://github.com/mozilla/fxa-auth-mailer/issues/54#issuecomment-117355682, we should send notices to dev-l10n and dev-l10n-web whenever we add news strings to be translated.  I don't think we should *entirely* automate this, but it'd be nice if the extract_strings.sh script could spit out a draft email highlighting the changes and remdind the runner of where to send it.

### PR DESCRIPTION
**Pull request by zaach**
Fixes #56.

@rfk r?

### CODE REVIEW

File: scripts/email.sh [hunk 1]
```diff
@@ -0,0 +1,50 @@
+# Script adapted from https://github.com/mozilla/olympia/blob/master/locale/omg_new_l10n.sh
+
+EMAIL_FROM="Firefox Accounts Developers <dev-fxacct@mozilla.org>"
+EMAIL_TO="Awesome Localizers <dev-l10n-web@lists.mozilla.org>"
+EMAIL_SUBJECT="[FXA] .po files updated"
```
Comment (rfk) [inline scripts/email.sh]: nit: "[FxA]"?  I'm not sure how consistent we've been with this in the past.

File: scripts/email.sh [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+echo $PWD
+
+echo "Calculating changes...."
+CHANGES=$(cat <<MAIL
+From: $EMAIL_FROM
+To: $EMAIL_TO
+Subject: $EMAIL_SUBJECT
+Hi,
+
+I am an automated script letting you know some .po files have just been
```
Comment (rfk) [inline scripts/email.sh]: nit: "know that some"

File: scripts/email.sh [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+echo "-----------------------------------------------"
+
+
+# Uses sendmail so we can set a real From address
+read -p "Do you want to send that to $EMAIL_TO?" -n 1 -r
+echo    # (optional) move to a new line
+if [[ $REPLY =~ ^[Yy]$ ]]
+then
+    echo "$CHANGES" | `which sendmail` -t
+fi
```
Comment (rfk) [inline scripts/email.sh]: It may be worth printing either "OK, email sent" or "Not sending" at the end of the script, so there's no confusion about what the final state was.

File: scripts/email.sh [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+CHANGES=$(cat <<MAIL
+From: $EMAIL_FROM
+To: $EMAIL_TO
+Subject: $EMAIL_SUBJECT
+Hi,
+
+I am an automated script letting you know some .po files have just been
+updated.  Unless something unusual is happening, we do bi-weekly pushes every other
+Wednesday so any strings committed by then will go live.  To give you an idea of
+the number of new strings I will calculate untranslated strings below.
```
Comment (rfk) [inline scripts/email.sh]: I'm assuming not, but is there any easy way to find out the number of new/changed strings since the last time we sent this email?

File: scripts/extract_strings.sh [hunk 5]
```diff
@@ -85,3 +85,6 @@ echo
 echo "Everything seems to be in order. Please check the extraction went okay then you can push the new branch with:"
 echo "cd $L10N_DIR"
 echo "git push <remote> merge-train-$TRAIN_NUMBER-strings"
+echo
+echo "When the strings have been merged, send an email to the l10n list by running:"
+echo "./scripts/email.sh"
```
Comment (rfk) [inline scripts/extract_strings.sh]: nit: it may be worth a slightly more descriptive name on this script, e.g. `email-dev-l10n.sh` or similar.

**Comment by rfk** [comment]
Thanks @zaach, this is great!  I'm r+ with nits on the overall shape of it, but I don't know enough about the mechanics of l10n to r? the details of the message generation.  @eoger would you mind having a quick look at this as well?

File: scripts/email.sh [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+MAIL
+)
+
+echo "-----------------------------------------------"
+echo "$CHANGES"
+echo "-----------------------------------------------"
+
+
+# Uses sendmail so we can set a real From address
+read -p "Do you want to send that to $EMAIL_TO?" -n 1 -r
```
Comment (eoger) [inline scripts/email.sh]: Maybe add " (y/n)" at the end of the prompt string

**Comment by eoger** [comment]
No objections.

**Comment by rfk** [comment]
cool; r+ with nits it is :-)
